spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/<databasename>
    username: <username>
    password: <password>
  jpa:
    hibernate:
      ddl-auto: create
      
server:
  port: 9001